version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acme_app
    ports:
      - "80:80"   # HTTP
      - "443:443"  # HTTPS
      - "1234:1234" # Python server port
    volumes:
      - ./acme:/var/www/html # Mount PHP files
      - ./svr-checker:/app   # Mount Python files
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    networks:
      - acme_network

networks:
  acme_network:
    driver: bridge
